### ISSUE TITLE
Scientific notation

### ISSUE THREAD

**Issue by dukei** [intellij-solidity/intellij-solidity#13]
Please add support for scientific notation:
`uint constant CAP = 14e6; //14000000`

Solidity supports it

**Comment by SerCeMan** [comment]
Hi, @dukei!

Thank you for the report. Before fixing the issue, let me ask you if you are interested in contributing to the plugin? If yes, I can guide you through the process and the issue you reported is a perfect point to start.

**Comment by dukei** [comment]
Yes, I would like to contribute. And would appreciate if you guide me.

**Comment by SerCeMan** [comment]
That's great!

Here I described the process for this particular issue, feel free to contact me using `sergeicelov@gmail.com` or any messenger app. 

First of all, you'll need to set up an IDE - IntelliJ Community should be enough, you will also need one plugin installed - https://github.com/JetBrains/Grammar-Kit. Then just open the project in IDE. 

The build system is gradle, there are few essential commands (it's possible to create a launch configuration to call them from IDE):

* `./gradlew build` - build
* `./gradlew check` - run tests
* `./gradlew runIdea` - compile solidity plugin and runs IntelliJ with it
* `./gradlew lexer` - regenerate lexer
* `./gradlew parser` - regenerate parser

The problem that there is no support for scientific notation in lexer and parser. The parser is generated from `src/main/grammars/solidity.bnf` file which contains solidity grammar definition, and you are interested in line 371:

```bnf
NumberLiteral ::= ( HexNumber | DecimalNumber | FixedNumber) NumberUnit?
```

There is no definition for a number literal written in scientific notation. You can create one, and in order to do that you will also need to modify lexer -  `src/main/grammars/_SolidityLexer.flex` using a decimal number definition as an example.

Once the work is done, you'll need to regenerate parsers using gradle. 

To validate that the implementation is correct, you can write a test or modify existing, `fixtures/parser/literals.sol` will probably be the best place to change. To do that, you will need to delete `fixtures/parser/literals.txt` file and run `me.serce.solidity.lang.core.SolidityCompleteCustomParsingTest#testLiterals`. It will create the text representation of parsed tree with the error. After fixing the notation and regenerating lexer/parser, instead of an error, the test will generate a proper tree.

**Comment by SerCeMan** [comment]
@dukei Feel free to send me a message if you need help with it.

**Comment by dukei** [comment]
Can I reach you via any messenger?
How can I run me.serce.solidity.lang.core.SolidityCompleteCustomParsingTest#testLiterals ?

**Comment by SerCeMan** [comment]
@dukei yep, my email is `sergeicelov@gmail.com`, skype: `gapro.`, telegram, vk and fb is also 👌 . 
Another option is gitter: https://gitter.im/intellij-solidity/intellij-solidity

You send me an email and we'll share accounts there  

> How can I run me.serce.solidity.lang.core.SolidityCompleteCustomParsingTest#testLiterals ?

The easiest way is to run it from IDE: 
![screen shot 2017-08-07 at 11 28 26 pm](https://user-images.githubusercontent.com/1780970/29028594-2b972ca2-7bc8-11e7-86c3-db8e748805de.png)

**Comment by SerCeMan** [comment]
It is also possible with `gradle` only:
```
./gradlew test --tests me.serce.solidity.lang.core.SolidityCompleteCustomParsingTest.testLiterals
```

**Comment by dukei** [comment]
https://github.com/intellij-solidity/intellij-solidity/commit/3f05e03f8a52672d31259e43fed93ae19bee230c
