### ISSUE TITLE
Version pragma should allow comparison operators

### ISSUE THREAD

**Issue by thevaleriemack** [intellij-solidity/intellij-solidity#168]
The pragmaAll element of the parser complains when writing a version pragma with a comparison operator to denote version range (>, <, =).

E.g.
`pragma solidity >=0.4.0 <0.6.0;`
Per [Solidity docs](https://solidity.readthedocs.io/en/latest/introduction-to-smart-contracts.html), this should be a valid form of indicating compiler compatibility with the file, as Solidity follows the semver standard: [see semver docs](https://docs.npmjs.com/misc/semver)

Also, the error message "pragmaAll expected, got <the_invalid_character>" is not very helpful. In particular because "pragmaAll" is not an entity in the Solidity language. I would change this to **"Invalid character in version pragma: <the_invalid_character>"**.

**Comment by SerCeMan** [comment]
Hey, @thevaleriemack! It was fixed in https://github.com/intellij-solidity/intellij-solidity/commit/7ea90de7bff71e5457ff70bbbf0d7505148c5e96. Yes, it's in the last release. You can either install it now from https://github.com/intellij-solidity/intellij-solidity/releases or wait until it's approved by JetBrains, it normally takes a few days.

**Comment by thevaleriemack** [comment]
Thanks!! Sorry I totally over looked the commit # attached
