### ISSUE TITLE
Errors when using immutable keyword

### ISSUE THREAD

**Issue by patitonar** [intellij-solidity/intellij-solidity#203]
When using the `immutable` keyword the plugin reports some errors. The solidity code is a valid code and compiles correctly. If I remove the `immutable` keywords the errors disappears and the contract still compiles correctly. I'm facing this issue also with the latest v2.3.0 version

Here is an example code to reproduce this:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.6.10;

contract Greeter {
    uint256 internal immutable testVar;

    constructor() public {
        testVar = 1;
    }
}
```

Screenshots with errors
![code](https://user-images.githubusercontent.com/4614574/90064831-b7487780-dcc1-11ea-9fff-ad9fec9c966c.png)
![errors](https://user-images.githubusercontent.com/4614574/90064834-badbfe80-dcc1-11ea-99de-ea4c5039aa1a.png)

**Comment by SerCeMan** [comment]
Hey, @patitonar! Yeah, it seems that the [grammar](https://github.com/intellij-solidity/intellij-solidity/blob/master/src/main/grammars/solidity.bnf) needs to be updated, should be a small fix. 

I can quickly fix it, but do you want to give it a go instead and send a PR? I can describe the steps that you can take to resolve this :)

**Comment by patitonar** [comment]
Sure! Please provide me some guidance on how to resolve this and I'll send a PR!

**Comment by SerCeMan** [comment]
Awesome! You'll need the plugin setup as described in [DEVELOPING.adoc#grammar](https://github.com/intellij-solidity/intellij-solidity/blob/master/DEVELOPING.adoc#grammar). 

Once you install the plugin, you'll get the highlighting with grammar. If you open Life Preview, you'll see something like the following: 
<img width="987" alt="Screen Shot 2020-08-13 at 11 19 18 pm" src="https://user-images.githubusercontent.com/1780970/90139438-ba279300-ddbb-11ea-8481-57d39a15fe11.png">

After fixing the grammar, take a look at the `VisibilityModifier`. Once you've fixed it, it'll parse correctly :) 
<img width="468" alt="Screen Shot 2020-08-13 at 11 24 58 pm" src="https://user-images.githubusercontent.com/1780970/90139890-4d60c880-ddbc-11ea-999f-e43df611f799.png">

After, you'll need the token to the lexer file `_SolidityLexer.flex` since it's a keyword, and then would be good to add a test to ensure that it parses correctly: [src/test/resources/fixtures/parser ](https://github.com/intellij-solidity/intellij-solidity/tree/master/src/test/resources/fixtures/parser), in this directory there are two files: *.sol - the program, and *.txt - the parsed AST. For each test, there is a corresponding method in [`parsingTest.kt`](https://github.com/intellij-solidity/intellij-solidity/blob/master/src/test/kotlin/me/serce/solidity/lang/core/parsingTest.kt#L19) You can add a test there and the change is good to go 🚀.
