### ISSUE TITLE
The bintray link to download EthereumJ is not valid

### ISSUE THREAD

**Issue by Eouo** [intellij-solidity/intellij-solidity#236]
插件的EVM需要怎么配置, 提示我不能下载,

**Comment by SerCeMan** [comment]
Hey, @iozhaq! Could you describe which exact issue you're experiencing? Also, if you could describe it in English - would be really helpful.

**Comment by iozhaq** [comment]
![image](https://user-images.githubusercontent.com/22764242/133062891-a8cd1f86-018c-4f1f-a110-36dc9cbed21d.png)
![image](https://user-images.githubusercontent.com/22764242/133063025-88673b57-100c-4cd7-8d81-fc8412b9e28e.png)
How can I solve it ?

**Comment by SerCeMan** [comment]
Thank you for reporting! I see the issue. [Bintray was deprecated](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), and the URL is explicitly hardcoded here: 
https://github.com/intellij-solidity/intellij-solidity/blob/c861bfff3b4e3281ae5b4dad34d6d61ead16733f/src/main/kotlin/me/serce/solidity/ide/settings/EvmDownloader.kt#L12

Unfortunately, this might not be easy to fix because ethereumj [was deprecated too](https://github.com/ethereum/ethereumj#no_entry-deprecated-no_entry), I'll see if there is any way to re-enable the functionality at low cost. But if it's not possible, this particular piece of functionality might need to be removed.

**Comment by burhancabiroglu** [comment]
Maybe you could use solc js vm.

**Comment by iozhaq** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by burhancabiroglu** [comment]
> Maybe you could use solc js vm.

@SerCeMan Maybe you could use solc js vm.

**Comment by baozidoufugan** [comment]
Can't Solidity integrate solidjs directly? Do I have to use solcjs through external tools?

**Comment by iozhaq** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mehr-licht** [comment]
How do we configure the EVM!?
The issue is closed but nothing was fixed and no alternative given!?

**Comment by SerCeMan** [comment]
Hi, @mehr-licht! Yes, that's correct. There is no way to configure Solidity tooling from the IDE only. The plugin, however, can be used in conjunction with any other available frameworks.

**Comment by lephyrius** [comment]
Why not just remove this option to stop the confusion?

**Comment by mbolotov** [comment]
EVM support was removed
