### ISSUE TITLE
Accept new constructor() syntax

### ISSUE THREAD

**Issue by rossng** [intellij-solidity/intellij-solidity#68]
The nightly versions of the Solidity compiler now use the `constructor(args)` instead of `function ContractName(args)` syntax. I tried to add this in intellij-solidity myself but I don't have enough time to get my head around how the parser generators work.

**Comment by SerCeMan** [comment]
I believe that this can be fixed by updating the grammar, some instructions can be found here: https://github.com/intellij-solidity/intellij-solidity/issues/13#issuecomment-320428416. I tried to find some docs on this, but it seems that even [grammar.txt](https://github.com/ethereum/solidity/blob/develop/docs/grammar.txt) in the solidity repo is not updated yet.

**Comment by ice1000** [comment]
Let me do this.

**Comment by ice1000** [comment]
Created a pull request that supports this syntax, but related completions are not included, awaiting further development.

**Comment by ice1000** [comment]
@SerCeMan Close this plz :stuck_out_tongue_winking_eye:
